### ISSUE TITLE
reporter timeout not working

### ISSUE THREAD

**Issue by pramodramdas** [openzipkin/zipkin-go#147]
When reporter is offline or down, timeout is not working. Rentry goes infinite as below.
 failed to send the request: Post http://localhost:9411/api/v2/spans: dial tcp 12
7.0.0.1:9411: connectex: No connection could be made because the target machine actively refused it.

 failed to send the request: Post http://localhost:9411/api/v2/spans: dial tcp 12
7.0.0.1:9411: connectex: No connection could be made because the target machine actively refused it.

 failed to send the request: Post http://localhost:9411/api/v2/spans: dial tcp 12
7.0.0.1:9411: connectex: No connection could be made because the target machine actively refused it.

As i can see default timeout is 5 seconds ie. defaultTimeout = time.Second * 5
And also i tried to override the timeout, which is not working
reporterTimeoutOption := zipkinHttpReporter.Timeout(time.Duration(5 * time.Second))
reporter := zipkinHttpReporter.NewReporter(os.Getenv("ZIPKIN_REPORTER"), reporterTimeoutOption)

**Comment by jcchavezs** [comment]
Thanks @pramodramdas for raising this issue. First of all I think this is not a bug but instead a feature, if the reporter fails to make a successful connection to the server then it will retry because tracing server being down is, IMO, a temporary situation. More so, recently [this PR](https://github.com/openzipkin/zipkin-go/pull/146) improved that feature by not creating goroutines on failing reporting.

Although I could not reproduce the specific error I tested myself that timeout is working when server is failing and it also works for when the request can't be performed (which is your case).
The infinite retry happens because of this: when we fail reporting the spans they [don't get removed](https://github.com/openzipkin/zipkin-go/blob/master/reporter/http/http.go#L163) (because the request could not be performed) but [instead we fail](https://github.com/openzipkin/zipkin-go/blob/master/reporter/http/http.go#L153) meaning that on the next tick of `batchInterval` (by default, 1 sec) the same spans are going to be retried and it becomes an infinite loop.

As for the infinite true, this mechanism can be definitively improved, an exponential backoff for when the server is down would be desirable in this situation (as far as I see it). We could also think of the reporter to retry for a certain time or a certain number of times, all that could be discussed in a feature request or we could happily support you over a contribution.

cc @basvanbeek @adriancole @skaslev

**Comment by pramodramdas** [comment]
Thanks @jcchavezs, as you mentioned exponential backoff or limiting re-entry times by passing options would be great to have, just like sockets. anyway thanks for the response.
