### ISSUE TITLE
Should Tracer create a real span for a not sampled context?

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#49]
At the moment, tracer is creating a noop span only if the tracer is set as noop. Otherwise, it is creating a real span (even if the context has `sampled=false`). This goes against the assumption that sampling reduces overhead as it creates `noop` objects.

Thoughts @basvanbeek @adriancole

**Comment by adriancole** [comment]
Answered in other thread, but noop span means doing no data collection. Due
to "firehose mode" which at least means making local aggregation possible,
we need a way to differentiate between not collecting data and not
reporting to (normal) zipkin. A noop span suits this as would an isNoop
flag. Another way could be to break it into parts like isRecording vs
isSampled etc. I have bias towards isNoop at the moment because there are
other things that use same terminology.

**Comment by jcchavezs** [comment]
So to be clear, we should create `noopSpan` when `sampled=false`, and since for the moment we don't support `firehose mode` we are doing that in any case.

@basvanbeek I will open a PR changing the `tracer.startSpan` and adding `IsNoop`. Is that alright?

**Comment by basvanbeek** [comment]
@jcchavezs Let's first let it marinate on what we want to do with firehose. I do not want to rush this.

**Comment by basvanbeek** [comment]
I've created a new issue for discussion on what we want to do with firehose mode in the future. 
see #58
