### ISSUE TITLE
Equivalent API for brave Tracer.joinSpan API

### ISSUE THREAD

**Issue by honghzzhang** [openzipkin/zipkin-go#50]
Is there an equivalent API in zipkin-go for brave Tracer API: 
Span joinSpan(TraceContext context) 

or a combination of the existing zipkin-go APIs that could achieve the same thing?

**Comment by jcchavezs** [comment]
We probably need something like https://github.com/opentracing/opentracing-go/blob/master/gocontext.go#L21.

Thoughts @basvanbeek ?

**Comment by honghzzhang** [comment]
@basvanbeek  Thanks! The examples are very helpful! One follow up question:
for the example of join span, should the spanName be the same name of the span it's joining? If yes, how do I find the name of that span? Or the span names can be different, as long as the span ID is the same which is the key identifier of a span.

**Comment by basvanbeek** [comment]
spanName can be and often is different between client side and server side of a span. If they are different, the server side takes priority in the Zipkin UI. 

The spanName is not propagated from service to service as it is not part of SpanContext / B3 propagation.

We have set the spanName as a required field due to its important. If you need to defer setting the span name you can add an empty string parameter there. 

Also please take a look at the middleware package inside the zipkin-go repository. It contains middleware wrappers for net/http.Client, net/http.Transport and net/http.Handler. As well as gRPC middlewares.

**Comment by basvanbeek** [comment]
Just a little snippet you can use/modify in case you want to use http.route naming together with gorilla/mux router:

```go
// ZipkinHTTPRoute sets http.route if a span and gorilla mux template path are
// found.
func ZipkinHTTPRoute(ctx context.Context, r *http.Request) context.Context {
	if span := zipkin.SpanFromContext(ctx); span != nil {
		if route := mux.CurrentRoute(r); route != nil {
			if tpl, err := route.GetPathTemplate(); err == nil {
				zipkin.TagHTTPRoute.Set(span, tpl)
				span.SetName(r.Method + " " + tpl)
			}
		}
	}
	return ctx
}
```

**Comment by honghzzhang** [comment]
Thanks much @basvanbeek for your help. Will take a look at the middleware package. 
Mark this issue as resolved/closed.
