### ISSUE TITLE
What is the right usage of TraceID.UnmarshalJSON()?

### ISSUE THREAD

**Issue by andy-zhangtao** [openzipkin/zipkin-go#73]
Hi, in my case, I use TraceID.UnmarshalJSON() to retrieve the origin traceid, but it doesn't work. 

For example:
```go
        var ss = "490f450433569020"
	t := new(zmodel.TraceID)
	t.UnmarshalJSON([]byte(ss))

	fmt.Println(t.String())
```
The result is: `0090f45043356902`. 

I check UnmarshalJSON source code, found `tID, err := TraceIDFromHex(string(traceID[1 : len(traceID)-1]))`

I don't know why need cut out the origin traceid?  But if I add 0 like this `var ss = "0490f4504335690200"`(add 0 in the begin and back). 

I got the expect result.

```go
        var ss = "0490f4504335690200"
	t := new(zmodel.TraceID)
	t.UnmarshalJSON([]byte(ss))

	fmt.Println(t.String())

        the result : 490f450433569020
```
Is it a bug? If not, can you please tell me the right usage?

**Comment by jcchavezs** [comment]
`UnmarshalJSON` is not intended to be used in such a way. The reason why `0490f4504335690200` becomes `490f450433569020` is because `UnmarshalJSON` trims of the first and the last character which are supposed to be quotes.

Remember that `UnmarshalJSON` is supposed to convert the JSON value into the actual value (by using json.Unmarshal in a struct`).

I still don't understand the case but if you wanna make your test pass you can do:

```go
var ss = `"490f450433569020"`
t := new(zmodel.TraceID)
t.UnmarshalJSON([]byte(ss))
fmt.Println(t.String())
```

**Comment by basvanbeek** [comment]
To add to the reply from @jcchavezs 

`490f450433569020` is not valid JSON. A valid JSON string is encoded as `"490f450433569020"`

I am curious about your use case for directly working with the trace identifiers. Are the propagation injectors and extractors as provided by the package not working for you?

**Comment by andy-zhangtao** [comment]
@jcchavezs Tks. I will change my code.  @basvanbeek  In my case, I want to use zipkin in go + nsq. But I am not found how to transfer span between Nsq Topic.   So I make a new SpanContext with traceid, id, parentid.

**Comment by jcchavezs** [comment]
@andy-zhangtao AFAIK nsq does not support headers in messages (like for example [kafka](https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers)). I think the only chance you have would be to include the trace context in the message body, Atlassian does this with kafka since they introduced zipkin before kafka supported messages. Check this: https://twitter.com/jcchavezs/status/994946024773963776

**Comment by basvanbeek** [comment]
@andy-zhangtao please also note that you'll need to follow the path as highlighted here:

https://github.com/openzipkin/openzipkin.github.io/blob/master/pages/instrumenting.md#message-tracing

**Comment by andy-zhangtao** [comment]
@jcchavezs @basvanbeek Thanks!!!  I will reference it.  Thanks Again!!
